namespace Dmt.DM.Mapper.Dto.PatientManage.PatVisit
{
    public class PatVisitDto
    {
        public string F_Pid { get; set; }
        public string F_Name { get; set; }
        public string F_Gender { get; set; }
        public string F_DialysisNo { get; set; }
        public string F_RecordNo { get; set; }
        public string F_BirthDay { get; set; }
        public string F_VisitDate { get; set; }
        public string F_VisitNo { get; set; }
        public string F_PatientSourse { get; set; }
        public string F_BedNo { get; set; }
        public string F_InpNo { get; set; }
        public string F_GroupName { get; set; }
        public string F_DialysisBedNo { get; set; }
        public string F_WeightSXTH { get; set; }
        public string F_FirstWeightTime { get; set; }
        public string F_LastWeightValue { get; set; }
        public string F_WeightTQ { get; set; }
        public string F_WeightYT { get; set; }
        public string F_WeightTH { get; set; }
        public string F_WeightST { get; set; }
        public string F_DialysisType { get; set; }
        public string F_ExchangeAmount { get; set; }
        public string F_ExchangeSpeed { get; set; }
        public string F_Machine { get; set; }
        public string F_DisinfectTime { get; set; }
        public string F_DisinfectPerson { get; set; }
        public string F_DialyzerType1 { get; set; }
        public string F_DialyzerType2 { get; set; }
        public string F_EstimateHours { get; set; }
        public string F_VascularAccess { get; set; }
        public string F_AccessName { get; set; }
        public string F_DialysisStartTime { get; set; }
        public string F_DialysisEndTime { get; set; }
        public string F_DialysisHours { get; set; }
        public string F_PuncturePerson { get; set; }
        public string F_StartPerson { get; set; }
        public string F_CheckPerson { get; set; }
        public string F_EndPerson { get; set; }
        public string F_HeparinType { get; set; }
        public string F_HeparinAmount { get; set; }
        public string F_HeparinUnit { get; set; }
        public string F_HeparinAddAmount { get; set; }
        public string F_HeparinAddSpeedUnit { get; set; }
        public string F_LowCa { get; set; }
        public string F_Ca { get; set; }
        public string F_K { get; set; }
        public string F_Na { get; set; }
        public string F_Hco3 { get; set; }
        public string F_BloodSpeed { get; set; }
        public string F_DialysateTemperature { get; set; }
        public string F_Nurse { get; set; }
        public string F_Doctor { get; set; }
        public string F_IsAcct { get; set; }
        public string F_IsCritical { get; set; }
        public string F_IsPrstring { get; set; }
        public string F_MachineShowAmount { get; set; }
        public string F_RealExchangeAmount { get; set; }
        public string F_DJMH { get; set; }
        public string F_DialyzerStatus { get; set; }
        public string F_FistulaStatus { get; set; }
        public string F_DuctOpeningStatus { get; set; }
        public string F_PatientStatus { get; set; }
        public string F_Reason { get; set; }
        public string F_SystolicPressure { get; set; }
        public string F_DiastolicPressure { get; set; }
        public string F_Pulse { get; set; }
        public string F_Temperature { get; set; }
        public string F_RecordDoctor { get; set; }
        public string F_DilutionType { get; set; }
        public string F_Memo { get; set; }
        public string F_PGwzsz { get; set; }
        public string F_PGxftz1 { get; set; }
        public string F_PGxftz2 { get; set; }
        public string F_PGxftz3 { get; set; }
        public string F_PGwzcx1 { get; set; }
        public string F_PGwzcx2 { get; set; }
        public string F_PGwzcx3 { get; set; }
        public string F_PGother { get; set; }
        public string F_IsArchive { get; set; }
        public string F_IsPrint { get; set; }
        public string F_EnabledMark { get; set; }
    }
}
